unit dataConsultas;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, dataTmpConexao, DB, SDEngine, JvMemoryDataset;

type
  TdmConsultas = class(TdmTmpConexao)
    SessaoConsultas: TSDSession;
    SQL: TSDQuery;
    qyProcDoencasPac: TSDQuery;
    qyProcDoencasPacexa_id: TStringField;
    qyProcDoencasPacsct_subcat: TStringField;
    qyProcDoencasPacsct_descabrev: TStringField;
    qyConsTpExame: TSDQuery;
    qyConsTpExameexa_id: TStringField;
    qyConsTpExameetp_id: TIntegerField;
    qyConsTpExameetp_abrev: TStringField;
    qyAtualizaProced: TSDQuery;
    qyAtualizaProcedexa_data: TDateField;
    qyAtualizaProcedexa_id: TStringField;
    qyAtualizaProcedprc_tuss: TIntegerField;
    qyAtualizaProcedexp_quant: TIntegerField;
    qyAtualizaProcedexp_unitario: TFloatField;
    qyAtualizaProcedexp_total: TFloatField;
    qyAtualizaProcedeco_valor: TFloatField;
    qyAtualizaProcedcov_codigo: TIntegerField;
    qyAtualizaProcedexp_id: TIntegerField;
    qyAtualizaProcedeco_status: TBooleanField;
    qyConsExamesPac: TSDQuery;
    qyConsExamesPacexa_id: TStringField;
    qyConsExamesPacsct_subcat: TStringField;
    qyConsExamesPacsct_descabrev: TStringField;
    qyProcExames: TSDQuery;
    qyProcExamesexa_id: TStringField;
    qyProcExamesexa_data: TDateField;
    qyProcExamespac_codigo: TIntegerField;
    qyProcExamespac_nome: TStringField;
    qyProcExamespac_idade: TSmallintField;
    qyProcExamespac_meses: TStringField;
    qyProcExamescov_codigo: TIntegerField;
    qyProcExamescov_descricao: TStringField;
    qyProcExamesexa_matricula: TStringField;
    qyProcExamesexa_guia: TStringField;
    qyProcExamesmed_codigo: TIntegerField;
    qyProcExamesmed_nome: TStringField;
    qyProcExamesexa_etapa: TIntegerField;
    qyProcExamesexa_prioridade: TIntegerField;
    qyProcExamesexa_dataprior: TDateField;
    qyProcExamesexa_obs: TStringField;
    qyProcExamesexa_origem: TIntegerField;
    qyProcExamesexl_descricao: TStringField;
    qyProcExamesexa_destino: TIntegerField;
    qyProcExamesexl_descricao_1: TStringField;
    qyProcExamesetp_id: TIntegerField;
    qyProcExamesetp_tipo: TStringField;
    qyProcExamesres_codigo: TIntegerField;
    qyProcExamesres_nome: TStringField;
    qyProcExamespac_sexo: TStringField;
    qyConsPacientesCad: TSDQuery;
    qyConsPacientesCadcodigo: TIntegerField;
    qyConsPacientesCadpaciente: TStringField;
    qyConsPacientesCadnascimento: TDateField;
    qyConsPacientesCadsexo: TStringField;
    qyConsMedicosCad: TSDQuery;
    qyConsDadosReq: TSDQuery;
    qyConsDadosReqexa_id: TStringField;
    qyConsDadosReqpac_codigo: TIntegerField;
    qyConsDadosReqpac_idade: TSmallintField;
    qyConsDadosReqpac_meses: TStringField;
    qyConsDadosReqcov_codigo: TIntegerField;
    qyConsDadosReqexa_matricula: TStringField;
    qyConsDadosReqexa_guia: TStringField;
    qyConsExames: TSDQuery;
    qyConsExamesexa_id: TStringField;
    qyConsExamesexa_data: TDateField;
    qyConsExamespac_codigo: TIntegerField;
    qyConsExamespac_nome: TStringField;
    qyConsExamespac_idade: TSmallintField;
    qyConsExamespac_meses: TStringField;
    qyConsExamescov_codigo: TIntegerField;
    qyConsExamescov_descricao: TStringField;
    qyConsExamesexa_matricula: TStringField;
    qyConsExamesexa_guia: TStringField;
    qyConsExamesmed_codigo: TIntegerField;
    qyConsExamesmed_nome: TStringField;
    qyConsExamesexa_etapa: TIntegerField;
    qyConsExamesexa_prioridade: TIntegerField;
    qyConsExamesexa_dataprior: TDateField;
    qyConsExamesexa_obs: TStringField;
    qyConsExamesexa_origem: TIntegerField;
    qyConsExamesexl_descricao: TStringField;
    qyConsExamesexa_destino: TIntegerField;
    qyConsExamesexl_descricao_1: TStringField;
    qyConsExamesetp_id: TIntegerField;
    qyConsExamesetp_tipo: TStringField;
    qyConsExamesres_codigo: TIntegerField;
    qyConsExamesres_nome: TStringField;
    qyConsExamespac_sexo: TStringField;
    qyProcMedCRM: TSDQuery;
    qyProcMedCRMmed_numconselho: TStringField;
    qyProcMedCRMmed_codigo: TIntegerField;
    qyProcMedCRMmed_nome: TStringField;
    qyConsNomePacEx: TSDQuery;
    qyConsNomePacExpac_nome: TStringField;
    qyConsEnvMail: TSDQuery;
    qyConsEnvMaileem_enviar: TBooleanField;
    qyConsEnvMailexa_id: TStringField;
    qyConsEnvMailexa_data: TDateField;
    qyConsEnvMailcov_descricao: TStringField;
    qyConsEnvMailmed_nome: TStringField;
    qyConsEnvMailpac_nome: TStringField;
    qyConsEnvMaileem_enviado: TBooleanField;
    qyConsEnvMailetp_id: TIntegerField;
    qyConsEnvMailcov_codigo: TIntegerField;
    qyConsEnvMailmed_codigo: TIntegerField;
    qyConsEnvMailpac_codigo: TIntegerField;
    qyConsEnvMailexa_etapa: TIntegerField;
    qyConsEnvMaileco_gerarcob: TBooleanField;
    updConsEnvMail: TSDUpdateSQL;
    qyConsEtapaCito: TSDQuery;
    tbExamesCito: TSDTable;
    tbExamesCitoexa_id: TStringField;
    tbExamesCitoexa_data: TDateField;
    tbExamesCitoexa_paciente: TStringField;
    tbExamesCitopac_idade: TSmallintField;
    tbExamesCitoexa_convenio: TStringField;
    tbExamesCitoexa_medico: TStringField;
    tbExamesCitoexa_dataprior: TDateField;
    tbExamesCitoexa_matricula: TStringField;
    tbExamesCitoexa_guia: TStringField;
    tbExamesCitopac_codigo: TIntegerField;
    tbExamesCitocov_codigo: TIntegerField;
    tbExamesCitomed_codigo: TIntegerField;
    tbExamesCitoexa_origem: TIntegerField;
    tbExamesCitoetp_id: TIntegerField;
    tbExamesCitoexa_etapa: TIntegerField;
    qyTabelas: TSDQuery;
    qyTabelastablename: TStringField;
    qyCampos: TSDQuery;
    qyCampostable_catalog: TStringField;
    qyCampostable_schema: TStringField;
    qyCampostable_name: TStringField;
    qyCamposcolumn_name: TStringField;
    qyCamposordinal_position: TIntegerField;
    qyCamposcolumn_default: TStringField;
    qyCamposis_nullable: TStringField;
    qyCamposdata_type: TStringField;
    qyCamposcharacter_maximum_length: TIntegerField;
    qyCamposcharacter_octet_length: TIntegerField;
    qyCamposnumeric_precision: TIntegerField;
    qyCamposnumeric_precision_radix: TIntegerField;
    qyCamposnumeric_scale: TIntegerField;
    qyCamposdatetime_precision: TIntegerField;
    qyCamposinterval_type: TStringField;
    qyCamposinterval_precision: TStringField;
    qyCamposcharacter_set_catalog: TStringField;
    qyCamposcharacter_set_schema: TStringField;
    qyCamposcharacter_set_name: TStringField;
    qyCamposcollation_catalog: TStringField;
    qyCamposcollation_schema: TStringField;
    qyCamposcollation_name: TStringField;
    qyCamposdomain_catalog: TStringField;
    qyCamposdomain_schema: TStringField;
    qyCamposdomain_name: TStringField;
    qyCamposudt_catalog: TStringField;
    qyCamposudt_schema: TStringField;
    qyCamposudt_name: TStringField;
    qyCamposscope_catalog: TStringField;
    qyCamposscope_schema: TStringField;
    qyCamposscope_name: TStringField;
    qyCamposmaximum_cardinality: TIntegerField;
    qyCamposdtd_identifier: TStringField;
    qyCamposis_self_referencing: TStringField;
    qyCamposis_identity: TStringField;
    qyCamposidentity_generation: TStringField;
    qyCamposidentity_start: TStringField;
    qyCamposidentity_increment: TStringField;
    qyCamposidentity_maximum: TStringField;
    qyCamposidentity_minimum: TStringField;
    qyCamposidentity_cycle: TStringField;
    qyCamposis_generated: TStringField;
    qyCamposgeneration_expression: TStringField;
    qyCamposis_updatable: TStringField;
    qyTamFisico: TSDQuery;
    qyTamFisicoesquema: TStringField;
    qyTamFisicotabela: TStringField;
    qyTamFisicotamanho: TMemoField;
    qyTamFisicotamanho_total: TMemoField;
    tbExamesHist: TSDTable;
    tbExamesHistexa_id: TStringField;
    tbExamesHistexa_data: TDateField;
    tbExamesHistexa_paciente: TStringField;
    tbExamesHistpac_idade: TSmallintField;
    tbExamesHistexa_convenio: TStringField;
    tbExamesHistexa_medico: TStringField;
    tbExamesHistexa_dataprior: TDateField;
    tbExamesHistexa_matricula: TStringField;
    tbExamesHistexa_guia: TStringField;
    tbExamesHistpac_codigo: TIntegerField;
    tbExamesHistcov_codigo: TIntegerField;
    tbExamesHistmed_codigo: TIntegerField;
    tbExamesHistexa_origem: TIntegerField;
    tbExamesHistetp_id: TIntegerField;
    tbExamesHistexa_etapa: TIntegerField;
    qyRelCorte: TSDQuery;
    qyRelCorteexa_id: TStringField;
    qyRelCorteexa_data: TDateField;
    qyRelCorteexa_prioridade: TIntegerField;
    qyRelCortetop_id: TIntegerField;
    qyRelCortetop_descricao: TStringField;
    qyRelCorteeth_id: TIntegerField;
    qyRelCorteeth_descricao: TStringField;
    qyRelCorteetg_seq: TIntegerField;
    qyRelCorteebl_seq: TIntegerField;
    qyRelCorteebl_fragmentos: TIntegerField;
    qyRelCorteebl_laminas: TIntegerField;
    qyConsEtapaHist: TSDQuery;
    qyRelExames: TSDQuery;
    qyRelExamesexa_id: TStringField;
    qyRelExamesexa_data: TDateField;
    qyRelExamesetp_tipo: TStringField;
    qyRelExamescov_descricao: TStringField;
    qyRelExamesmed_nome: TStringField;
    qyRelExamespac_nome: TStringField;
    qyRelExameseem_concluido: TBooleanField;
    qyRelExamesOrig: TSDQuery;
    StringField1: TStringField;
    DateField1: TDateField;
    StringField2: TStringField;
    StringField3: TStringField;
    StringField4: TStringField;
    StringField5: TStringField;
    BooleanField1: TBooleanField;
    qyRelExamesOrigexl_descricao: TStringField;
    qyRelListagem: TSDQuery;
    qyRelListagemexa_id: TStringField;
    qyRelListagempac_nome: TStringField;
    qyRelListagemcov_descricao: TStringField;
    qyRelListagemexa_data: TDateField;
    qyRelExProced: TSDQuery;
    qyRelExProcedexa_data: TDateField;
    qyRelExProcedexa_id: TStringField;
    qyRelExProcedexp_quant: TIntegerField;
    qyRelExProcedprc_tuss: TIntegerField;
    qyRelExProcedprc_descricao: TStringField;
    qyRelExProcedexp_unitario: TFloatField;
    qyRelExProcedexp_total: TFloatField;
    qyConsSaldoCaixa: TSDQuery;
    qyCaixaAgrup: TSDQuery;
    qyCaixaAgrupmov_codigo: TIntegerField;
    qyCaixaAgrupmov_descricao: TStringField;
    qyCaixaAgrupsum: TFloatField;
    qySaldos: TSDQuery;
    qySaldoscon_descricao: TStringField;
    qySaldoscon_codigo: TIntegerField;
    qySaldossum: TFloatField;
    qyRelLotesTISS: TSDQuery;
    qyRelLotesTISSrti_id: TIntegerField;
    qyRelLotesTISSrec_codigo: TIntegerField;
    qyRelLotesTISSrti_gerado: TBooleanField;
    qyRelLotesTISSrti_lote: TIntegerField;
    qyRelLotesTISSrti_nguias: TIntegerField;
    qyRelLotesTISSrec_vencimento: TDateField;
    qyRelLotesTISSrec_nome: TStringField;
    qyRelLotesTISSrec_valor: TFloatField;
    qyRelLotesTISSrec_status: TStringField;
    qyConsExamesConv: TSDQuery;
    qyConsExamesConvexa_id: TStringField;
    qyConsExamesConvpac_nome: TStringField;
    qyConsExamesConvexp_quant: TIntegerField;
    qyConsExamesConvprc_descricao: TStringField;
    qyConsExamesConvexp_unitario: TFloatField;
    qyConsExamesConvexp_total: TFloatField;
    qyConsRecProced: TSDQuery;
    qyConsRecProcedexa_id: TStringField;
    qyConsRecProcedpac_nome: TStringField;
    qyConsRecProcedexp_quant: TIntegerField;
    qyConsRecProcedprc_descricao: TStringField;
    qyConsRecProcedexp_unitario: TFloatField;
    qyConsRecProcedexp_total: TFloatField;
    qyConsCitoEtapas: TSDQuery;
    qyConsCitoEtapasexa_id: TStringField;
    qyConsCitoEtapasexa_data: TDateField;
    qyConsCitoEtapasmed_nome: TStringField;
    qyConsCitoEtapaspac_nome: TStringField;
    qyConsCitoEtapascov_descricao: TStringField;
    qyConsCitoEtapasexa_etapa: TIntegerField;
    qyConsCitoEtapascet_descricao: TStringField;
    qyConsCitoEtapasetp_id: TIntegerField;
    qyConsCitoEtapasmed_codigo: TIntegerField;
    qyConsCitoEtapaspac_codigo: TIntegerField;
    qyConsCitoEtapascov_codigo: TIntegerField;
    qyConsHistoEtapas: TSDQuery;
    qyConsHistoEtapasexa_id: TStringField;
    qyConsHistoEtapasexa_data: TDateField;
    qyConsHistoEtapasmed_nome: TStringField;
    qyConsHistoEtapaspac_nome: TStringField;
    qyConsHistoEtapascov_descricao: TStringField;
    qyConsHistoEtapasexa_etapa: TIntegerField;
    qyConsHistoEtapashet_descricao: TStringField;
    qyConsHistoEtapasetp_id: TIntegerField;
    qyConsHistoEtapasmed_codigo: TIntegerField;
    qyConsHistoEtapaspac_codigo: TIntegerField;
    qyConsHistoEtapascov_codigo: TIntegerField;
    qyConsImunoEtapas: TSDQuery;
    qyConsImunoEtapasexa_id: TStringField;
    qyConsImunoEtapasexa_data: TDateField;
    qyConsImunoEtapasmed_nome: TStringField;
    qyConsImunoEtapaspac_nome: TStringField;
    qyConsImunoEtapascov_descricao: TStringField;
    qyConsImunoEtapasexa_etapa: TIntegerField;
    qyConsImunoEtapasimu_descricao: TStringField;
    qyConsImunoEtapasetp_id: TIntegerField;
    qyConsImunoEtapasmed_codigo: TIntegerField;
    qyConsImunoEtapaspac_codigo: TIntegerField;
    qyConsImunoEtapascov_codigo: TIntegerField;
    qyConsDivExames: TSDQuery;
    qyConsLogs: TSDQuery;
    qyConsEtapaExame: TSDQuery;
    qyConsUltAlt: TSDQuery;
    qyConsDivExamesexa_id: TStringField;
    qyConsDivExamesexa_data: TDateField;
    qyConsDivExamespac_codigo: TIntegerField;
    qyConsDivExamespac_nome: TStringField;
    qyConsDivExamespac_dtnasc: TDateField;
    qyConsDivExamespac_idade: TSmallintField;
    qyConsDivExamespac_meses: TStringField;
    qyConsDivExamescov_codigo: TIntegerField;
    qyConsDivExamesexa_matricula: TStringField;
    qyConsDivExamesexa_guia: TStringField;
    qyConsDivExamesmed_codigo: TIntegerField;
    qyConsDivExamesexa_etapa: TIntegerField;
    qyConsDivExamesexa_prioridade: TIntegerField;
    qyConsDivExamesexa_dataprior: TDateField;
    qyConsDivExamesexa_obs: TStringField;
    qyConsDivExamesexa_origem: TIntegerField;
    qyConsDivExamesexa_destino: TIntegerField;
    qyConsDivExamesetp_id: TIntegerField;
    qyConsDivExamesres_codigo: TIntegerField;
    qyIntegridade: TSDQuery;
    qyIntegridadeexa_id: TStringField;
    qyIntegridadeexa_data: TDateField;
    qyExamesSolic: TSDQuery;
    qyConsQuantEx: TSDQuery;
    qyConsQuantExexa_data: TDateField;
    qyConsQuantExcount: TLargeintField;
    qyConsPagar: TSDQuery;
    qyConsPagarpag_vencimento: TDateField;
    qyConsPagarpag_nf: TIntegerField;
    qyConsPagarpag_parcela: TIntegerField;
    qyConsPagarpag_fornecedor: TStringField;
    qyConsPagarpag_valor: TFloatField;
    qyConsPagarpag_acrescimo: TFloatField;
    qyConsPagarpag_desconto: TFloatField;
    qyConsPagarpag_pago: TFloatField;
    qyConsPagarpag_saldo: TFloatField;
    qyConsPagarpag_emissao: TDateField;
    qyConsPagarfor_codigo: TIntegerField;
    qyConsPagarpag_status: TStringField;
    qyConsPendTISS: TSDQuery;
    qyConsPendTISSexa_id: TStringField;
    qyConsPendTISSexa_data: TDateField;
    qyConsPendTISStpd_descricao: TStringField;
    qyConsPendTISSpac_nome: TStringField;
    qyConsPendTISSmed_nome: TStringField;
    qyConsPendTISScov_descricao: TStringField;
    qyConsPendTISSetp_id: TIntegerField;
    qyConsGeraCob: TSDQuery;
    qyConsGeraCobexa_id: TStringField;
    qyConsGeraCobexa_paciente: TStringField;
    qyConsGeraCobexa_medico: TStringField;
    qyConsGeraCobeco_valor: TFloatField;
    qyConsGeraCobexa_guia: TStringField;
    qyConsGeraCobexa_convenio: TStringField;
    qyConsGeraCobeco_gerarcob: TBooleanField;
    qyConsGeraCobeco_vlrpago: TFloatField;
    qyConsGeraCobeco_status: TBooleanField;
    qyConsGeraCobpac_codigo: TIntegerField;
    qyConsGeraCobmed_codigo: TIntegerField;
    qyConsGeraCobcov_codigo: TIntegerField;
    qyConsGeraCobetp_id: TIntegerField;
    qyConsGeraCobexa_etapa: TIntegerField;
    qyConsReceber: TSDQuery;
    qyConsReceberrec_emissao: TDateField;
    qyConsReceberrec_vencimento: TDateField;
    qyConsReceberrec_nome: TStringField;
    qyConsReceberrec_codigo: TIntegerField;
    qyConsReceberhis_id: TIntegerField;
    qyConsReceberrec_valor: TFloatField;
    qyConsReceberrec_acrescimo: TFloatField;
    qyConsReceberrec_desconto: TFloatField;
    qyConsReceberrec_pago: TFloatField;
    qyConsReceberrec_saldo: TFloatField;
    qyConsReceberrec_status: TStringField;
    qyConsRecebercov_codigo: TIntegerField;
    qyConsReceberrec_codcliente: TIntegerField;
    qyConsRecebercob_codigo: TIntegerField;
    qyConsRecExames: TSDQuery;
    qyConsRecExameshis_item: TIntegerField;
    qyConsRecExamesexa_id: TStringField;
    qyConsRecExameshis_paciente: TStringField;
    qyConsRecExameshis_valor: TFloatField;
    qyConsRecExameshis_status: TStringField;
    qyConsRecExameshis_medico: TStringField;
    qyConsRecExameshis_id: TIntegerField;
    qyConsRecExameshis_data: TDateField;
    qyConsRecExamescov_codigo: TIntegerField;
    qyConsRecExamespac_codigo: TIntegerField;
    qyConsRecExameshis_gercob: TStringField;
    qyConsRecExamesmed_codigo: TIntegerField;
    TempGeraCob: TJvMemoryData;
    TempGeraCobexa_id: TStringField;
    TempGeraCobexa_paciente: TStringField;
    TempGeraCobexa_valor: TFloatField;
    updConsGeraCob: TSDUpdateSQL;
    qyConsRecObs: TSDQuery;
    qyConsRecObsrob_data: TDateField;
    qyConsRecObsrob_obs: TStringField;
    qyConsRecObsrob_id: TIntegerField;
    qyConsRecObsrec_codigo: TIntegerField;
    qyExportaCob: TSDQuery;
    qyExportaCobpac_nome: TStringField;
    qyExportaCobpac_idade: TSmallintField;
    qyExportaCobexa_id: TStringField;
    qyExportaCobexa_data: TDateField;
    qyExportaCobmed_nome: TStringField;
    qyExportaCobmed_numconselho: TStringField;
    qyExportaCobcov_descricao: TStringField;
    qyExportaCobexa_guia: TStringField;
    qyExportaCobexa_matricula: TStringField;
    qyExportaCobexp_quant: TIntegerField;
    qyExportaCobprc_tuss: TIntegerField;
    qyExportaCobprc_descricao: TStringField;
    qyExportaCobexp_unitario: TFloatField;
    qyExportaCobexp_total: TFloatField;
    qyConsDivExamescov_descricao: TStringField;
    qyConsDivExamesmed_nome: TStringField;
    qyConsDivExamesexl_descricao: TStringField;
    updConsDivExames: TSDUpdateSQL;
    qyConsTopografias: TSDQuery;
    qyConsTopografiasexa_id: TStringField;
    qyConsTopografiasmat_descricao: TStringField;
    qyConsTopografiastop_descricao: TStringField;
    qyConsTopografiasehi_quant: TIntegerField;
    qyConsTopografiaseio_descricao: TStringField;
    qyConsTopografiaseth_descricao: TStringField;
    qyConsTopografiassum: TLargeintField;
    qyConsTopografiassum_1: TLargeintField;
    qyRelAuditoriaH: TSDQuery;
    qyRelAuditoriaHmat_descricao: TStringField;
    qyRelAuditoriaHehi_quant: TIntegerField;
    qyRelAuditoriaHeio_descricao: TStringField;
    qyRelAuditoriaHeth_descricao: TStringField;
    qyRelAuditoriaHsum: TLargeintField;
    procedure qyConsDivExamesAfterPost(DataSet: TDataSet);
    procedure qyConsDivExamesBeforePost(DataSet: TDataSet);
    procedure qyConsDivExamesPostError(DataSet: TDataSet; E: EDatabaseError;
      var Action: TDataAction);
    procedure qyConsDivExamesUpdateError(DataSet: TDataSet; E: EDatabaseError;
      UpdateKind: TUpdateKind; var UpdateAction: TUpdateAction);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  dmConsultas: TdmConsultas;

implementation

{$R *.dfm}

uses dataLookups;
//uses uDaoConsEnvMail, dataLookups;

procedure TdmConsultas.qyConsDivExamesAfterPost(DataSet: TDataSet);
begin
  qyConsDivExames.ApplyUpdates;
  if database.InTransaction then
    database.Commit
  else
  Begin
    database.StartTransaction;
    database.Commit
  end;
  qyConsDivExames.CommitUpdates;
end;

procedure TdmConsultas.qyConsDivExamesBeforePost(DataSet: TDataSet);
begin
  database.StartTransaction;
end;

procedure TdmConsultas.qyConsDivExamesPostError(DataSet: TDataSet;
  E: EDatabaseError; var Action: TDataAction);
begin
  database.Rollback;
end;

procedure TdmConsultas.qyConsDivExamesUpdateError(DataSet: TDataSet;
  E: EDatabaseError; UpdateKind: TUpdateKind; var UpdateAction: TUpdateAction);
begin
  database.Rollback;
  qyConsDivExames.RollbackUpdates;
end;

end.
